# Generated by Django 5.2 on 2025-04-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='description',
        ),
    ]
