# Generated by Django 5.2 on 2025-05-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
