# Generated by Django 5.2 on 2025-05-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_status',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('done', 'Done'), ('postponed', 'Postponed')], max_length=100, null=True),
        ),
    ]
